### ISSUE TITLE
Konsole: Workaround for bug #15 no longer needed 

### ISSUE THREAD

**Issue by nairaner** [brezerk/q4wine#87] opened 2016-09-18 12:02 UTC
Behavior when using argument -e is fixed, which caused workaround to stop working and using the default command now works

**Comment by brezerk** [comment] 2016-09-20 09:56
Thank you for reporting. Will take a look on it at the evening.

**Comment by brezerk** [comment] 2016-09-20 19:22
Hi @nairaner 

Are you talking about `gnom-terminal` app, is it correct? Can you provide me correct arguments example please?

**Comment by nairaner** [comment] 2016-09-20 21:22
I'm talking about konsola. After some update i couldnt start debug and notice that issue and used konsola1 to start it correctly.

**Comment by brezerk** [comment] 2016-09-21 16:46
hm.......

@nairaner what version are you using?

```
[ himera ] brezerk@pts/3:3  ~ $
> 09/21/16 19:43:05 EEST > konsole -v    
Qt: 5.6.1
KDE Frameworks: 5.25.0
Konsole: 16.04.3
```

and it still require -e command to execute cmd

```
  -e <cmd>                  Command to execute. This option will catch all following arguments, so use it as the last option.
```

**Comment by nairaner** [comment] 2016-09-21 22:30
I mean commit 865ded03bbf7aff9e84d7788f8497a1120089da1
I linked konsole1 to konsole and now this works for me 
```
/usr/bin/konsole1 --noclose -e " /usr/bin/env  WINEPREFIX='/home/nairaner/.wine'  WINESERVER='/usr/bin/wineserver'  WINELOADER='/usr/bin/wine'  WINEARCH='Default'  WINEDEBUG='-all'  WINEDLLOVERRIDES=''  LANG=''  /bin/sh -c \"cd '/home/nairaner' && /usr/bin/nice -n 10 /usr/bin/wine  explorer.exe /desktop=winecfg,800x600  'winecfg' -h 2>&1 \" "
```
And this doesnt
```
/usr/bin/konsole --noclose -e /bin/sh -c  " /usr/bin/env  WINEPREFIX='/home/nairaner/.wine'  WINESERVER='/usr/bin/wineserver'  WINELOADER='/usr/bin/wine'  WINEARCH='Default'  WINEDEBUG='-all'  WINEDLLOVERRIDES=''  LANG=''  /bin/sh -c \"cd '/home/nairaner' && /usr/bin/nice -n 10 /usr/bin/wine  explorer.exe /desktop=winecfg,800x600  'winecfg' -h 2>&1 \" "
```

**Comment by brezerk** [comment] 2016-09-24 15:48
Reproduced with 16.08.1
Working on workaround now.

**Comment by brezerk** [comment] 2016-09-24 21:01
hm.... @nairaner if I am getting it correctly, this is konsole bug.

```
  -e <cmd>                   Command to execute. This option will catch all
                             following arguments, so use it as the last option.
```

So it says: **This option will catch all following arguments** however, it actually does not follow expected behavior:

```
[ himera ] brezerk@pts/0:9  ~ $
> 09/24/16 23:59:06 EEST > konsole -v                      
konsole 16.08.1
[ himera ] brezerk@pts/0:10  ~ $
> 09/24/16 23:59:54 EEST > konsole -e /bin/sh -c 'echo lol'
Unknown option 'c'.
[ himera ] brezerk@pts/0:11 :( 1 ~ $
> 09/24/16 23:59:56 EEST > /bin/sh -c 'echo lol'           
lol
[ himera ] brezerk@pts/0:12  ~ $
```

**Comment by brezerk** [comment] 2016-09-24 21:20
https://bugs.kde.org/show_bug.cgi?id=369297

**Comment by brezerk** [comment] 2016-09-24 21:43
oh. yeah: https://bugs.kde.org/show_bug.cgi?id=366793

**Comment by nairaner** [comment] 2016-09-25 13:44
But is there a point using 
```
/usr/bin/konsole --noclose -e /bin/sh -c  $command
```
instead of just 
```
/usr/bin/konsole --noclose -e $command
```
which works on newer version of konsole and was introduced as a workaround for a ?bug? in 2012?
Both work correctly in 
````
Qt: 5.7.0
KDE Frameworks: 5.26.0
Konsole: 16.04.3
```
and latter works also in 16.08.1

**Comment by brezerk** [comment] 2016-09-25 19:08
*sigh* 

I believe there was a reason of adding this `-e /bin/sh -c` ugly logic.

yeah. here your are: https://github.com/brezerk/q4wine/issues/15#issuecomment-10964079

so just 
```
/usr/bin/konsole --noclose -e $command
```

does not work as expected in the 4.10 Konsole :( So reverting this workaround will cause problems for KDE 4.x users. (I can't confirm that is was fixed in 4.10+ unfortunately)

That's the tricky part: I am not sure how to keep both KDE4 and KDE5 working without 366793 being fixed on KDE side =\

**Comment by Gfurst** [comment] 2017-02-12 21:40
Is there any working for this atm?

**Comment by brezerk** [comment] 2017-02-14 11:59
hi @Gfurst afik this has been fixed by KDE team: https://bugs.kde.org/show_bug.cgi?id=366793 (not sure when it will be released).

As a temporary workaround: you may wish to use `xterm` instead of `konsole`.

**Comment by brezerk** [comment] 2017-09-24 11:59
this bug seems to be fixed by KDE team. So I am going to close this one. Any objections?

**Comment by nairaner** [comment] 2017-09-27 20:32
I dont see a reason not to

**Comment by brezerk** [comment] 2017-09-28 21:29
ty. closing.

**Closed** 2017-09-28 21:29 UTC
Labels: Bug, Reproduced
