### ISSUE TITLE
"wine settings" (paths) not saved on first run

### ISSUE THREAD

**Issue by xenithorb** [brezerk/q4wine#73] opened 2016-04-11 21:39 UTC
```
rpm -qa | grep q4wine
q4wine-1.1-8.r2.fc23.x86_64
```
OS: Fedora 23 

Tried on two of my F23 systems to confirm, using KDE Plasma 5, 

Paths for: Binary, Server, Loader, Libs (32bit), Libs (64bit) are not saved 

After setting them again in Options -> General, they are saved and work properly.

**Comment by brezerk** [comment] 2016-04-20 11:55
Hi @xenithorb,

I am really sorry for a late response: I am currently searching for a new job, so I will not be able to take a look on this issue till the end of the week.

**Comment by xenithorb** [comment] 2016-04-20 12:00
No problem, same here. Thanks for the ACK!

**Comment by brezerk** [comment] 2016-04-25 20:06
Hi @xenithorb ,

It looks like a duplication of issue: https://github.com/brezerk/q4wine/issues/50 
It was fixed in 1.2-r1+ releases.

Can you try 1.2-r1 ( or better 1.3.1 :) ) to see is if it still can be reproduced?

**Comment by xenithorb** [comment] 2016-04-25 20:43
Yep that's likely the case. I'm dealing with `q4wine-1.1-8.r2.fc23.x86_64.rpm` on Fedora, so I'll have to go give the maintainer a poke. Feel free to close or I can come back and test when I have the time to get a newer build going. `q4wine-1.1-10.r2.fc24.x86_64.rpm` is still in upcoming F24 so this does need to be dealt with

**Comment by brezerk** [comment] 2016-05-17 14:30
Closing per reported suggestion. Reopen if needed.

**Closed by brezerk** 2016-05-17 14:30 UTC
Labels: Bug
