### ISSUE TITLE
Problem opening file dialog to mount ISO

### ISSUE THREAD

**Issue by cebxan** [brezerk/q4wine#86] opened 2016-09-10 02:48 UTC
When trying to mount an ISO image through Mount ISO -> Mount -> Browse I get a very brief glimpse of a modal dialog and then nothing else. Running in the terminal I get this message:
```
SqlError:  QSqlError("", "Parameter count mismatch", "")
QFile::link: Empty or null file name
```
Trying to add the ISO through the Disc Image Manager, I get the Open File dialog and select an ISO, but, after accepting, the list shows a new row with an empty Disc Image Name and size of 0 MB.

I'm using ArchLinux with the following packages.
```
qt4 4.8.7-9
qt5-base 5.7.0-2
wine-staging 1.9.18-1
winetricks 20160724-1
wine-mono 4.6.3-1
wine_gecko 2.47-1
fuseiso 20070708-6
q4wine 1.3.2-1
```
Thank you very much for your help!

**Comment by brezerk** [comment] 2016-09-12 07:53
Hi @cebxan 

Thanks for bug report.

Can you show output for `q4wine-cli -v` please?

Thanks

**Comment by cebxan** [comment] 2016-09-12 07:57
Hi @brezerk , I'm pasting the output:

```
❯ q4wine-cli -v
[ii] Loading translation:  "q4wine_en_US"
q4wine-cli 1.3.2
Copyright (C) 2008-2016 by Alexey S. Malakhov <brezerk@gmail.com>
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Buildtime flags are:

 CMAKE_INSTALL_PREFIX    /usr                     

 QT5                     ON                       
 RELEASE                 ON                       
 DEBUG                   OFF                      
 WITH_ICOUTILS           ON                       
 WITH_SYSTEM_SINGLEAPP   OFF                      
 WITH_WINEAPPDB          ON                       
 WITH_DBUS               ON                       

Author: Alexey S. Malakhov.
```
Thanks!

**Comment by brezerk** [comment] 2016-09-12 19:08
hm.... I have tried to reproduce. and had no luck :( It seems like you have corrupted database or config file.

@cebxan can you send me q4wine's config file and it's database snapshot on my email : brezerk@gmail.com  please?

config file:
`$HOME/.config/q4wine/default.conf`

database:
`$HOME/.config/q4wine/db/generic.dat`

thanks!

**Comment by brezerk** [comment] 2016-09-13 20:49
Hi @cebxan 

Thank you for the report and for the files.

The issue related to the Qt5 behavior.
For some reasons, `QAction->text()` returns test with Shortcut symbol. Even it there was no Shortcut symbol set! WHAT???

this leads to the logic confusions: for example expected device name `/dev/sr0` becomes `/&dev/sr0`.

This commit: https://github.com/brezerk/q4wine/commit/ab5659a5333a160a354888f9ec18d9e9cbe1274d should fix this issue. 

Let me know if it does not work for you.

**Comment by nairaner** [comment] 2016-09-21 22:35
For me it is fixed as well as crash when using "Run"

**Comment by brezerk** [comment] 2016-09-24 15:49
Yeah. There was same root cause also.
I am going to close this ticket. 
Reopen if needed.

**Closed by brezerk** 2016-09-24 15:49 UTC
Labels: Bug

**Comment by cebxan** [comment] 2016-09-24 16:55
I'm sorry for the delay. Yes! This is fixed for me too.

Thank you very much! 😀

**Comment by brezerk** [comment] 2016-09-24 21:35
ur'welcome. thanks for confirmation :)
