### ISSUE TITLE
Links imported from Windows desktop do not work

### ISSUE THREAD

**Issue by ktamp** [brezerk/q4wine#103] opened 2016-11-21 19:14 UTC
E.g. installing game Syberia from GOG creates a desktop link which is imported by Q4Wine.
Trying to open this link causes error -1.

The actual command issued by Q4Wine to run Syberia is:

`/usr/bin/env  WINEPREFIX='/home/ktamp/.wine'  WINESERVER='/usr/bin/wineserver'  WINELOADER='/usr/bin/wine'  WINEDLLPATH='/usr/lib32/wine/'  WINEARCH='win32'  WINEDEBUG='-all'  /bin/sh -c "cd '/home/ktamp/.wine/dosdevices/c:/GOG Games/Syberia/' &&   '/usr/bin/wine'   'C:\windows\command\start.exe Unix homektamp.winedosdevicesc:usersPublicDesktopSyberia.lnk'  2>&1 "`

The culprit here is in the last part:
`'C:\windows\command\start.exe Unix homektamp.winedosdevicesc:usersPublicDesktopSyberia.lnk'`

If this is split in two and the second part is simplified (while adding missing backslashes), it works:
`'C:\windows\command\start.exe' 'c:\users\Public\Desktop\Syberia.lnk'`

**Comment by brezerk** [comment] 2016-11-21 22:16
hi @ktamp 

there should be Syberia.desktop file located at `/home/ktamp/.wine/dosdevices/c:/users/ktamp/Desktop` can you send me it please?

**Comment by brezerk** [comment] 2016-11-21 22:52
Ok.

Good news: I was able to reproduce this with the other game downloaded from GOG.
Bad news: now I have to walk through this game before I will create a fix for this issue... >_<

**Comment by brezerk** [comment] 2016-11-21 23:28
This issue was caused by odd regexp parser: the '/unix /home...' should be passed as arguments to start.exe.

This commit: https://github.com/brezerk/q4wine/commit/82de0db7716f8717f7f57991bdfb15c0e983548a should fix the issue. **Note** you will need to remove imported icons in the `import` folder manually before testing the fix.

**Comment by ktamp** [comment] 2016-11-22 18:52
I confirm it is working now. Thank you for this quick fix!

**Comment by brezerk** [comment] 2016-11-22 21:47
ur'welcome. thanks for bug report.

**Closed by brezerk** 2016-11-22 21:47 UTC
Labels: Bug
