### ISSUE TITLE
[Qt5] Segfault when exit the q4wine application

### ISSUE THREAD

**Issue by sl1pkn07** [brezerk/q4wine#55] opened 2015-03-22 12:17 UTC
when exit the q4wine application with 'file -> Exit' menu or press Ctl+Q gets segfault

    [2129289.599945] Qt bearer threa[28055]: segfault at 3afe8e08 ip 00007f29585c2100 sp 00007f2944811e70 error 4 in libc-2.21.so[7f295858c000+199000]
    [2131734.917901] traps: q4wine[9320] trap invalid opcode ip:7fb554b0af10 sp:7fff96a4d918 error:0 in libQt5Core.so.5.4.1[7fb5547a6000+4c1000]
    [2131842.036220] traps: q4wine[10424] trap invalid opcode ip:7f7d92073f10 sp:7fff0caa43c8 error:0 in libQt5Core.so.5.4.1[7f7d91d0f000+4c1000]
    [2132172.561626] q4wine[19567]: segfault at 22e4310 ip 00000000022e4310 sp 00007fff599cbba8 error 15
    [2132221.822510] q4wine[29397]: segfault at 18 ip 0000000000000018 sp 00007fffd5de7508 error 14 in q4wine[400000+208000]

e53bf788c94a720a235d01bde03c1fbf556f0637 build with Qt5 5.4.1

greetings

**Comment by skybon** [comment] 2015-03-22 18:56
Thank you for your bug report.

I cannot reproduce with Q4Wine built against Qt 5.4.1, Arch Linux x86-64. Could you please try with an empty q4wine config.

**Comment by sl1pkn07** [comment] 2015-03-22 19:04
yes. with clean config the segfault is gone

is possible export the old config/shortcuts to new ones?

i use archlinux too (i am  [AUR] maintainer  https://aur.archlinux.org/packages/?O=0&C=0&SeB=nd&K=q4wine&outdated=&SB=a&SO=d&PP=250&do_Search=Go)

**Comment by skybon** [comment] 2015-03-22 19:06
Hm, I can reproduce this issue after trying to updating winetricks list.

**Comment by sl1pkn07** [comment] 2015-03-22 19:08
yes. i move my winetricks script and the segfault is back

**Comment by skybon** [comment] 2015-03-22 19:10
dupe of #53.

**Closed by skybon** 2015-03-22 19:10 UTC
