### ISSUE TITLE
unhandled page fault on read access to 0x00000000

### ISSUE THREAD

**Issue by Erhie** [brezerk/q4wine#88] opened 2016-09-18 13:27 UTC
Hello,
I want to install the game Dinosaur World from BBC-Science
with WINE on OpenSuse
All my afforts with helper software, also with q4wine result in
_unhandled page fault on read access to 0x00000000_

It is a nice 3D game for children programmed for Win2k

Have you an idea to fix such error?

Thank you so much
Erhy

**Comment by brezerk** [comment] 2016-09-20 09:58
Hi @Erhie 

Can you add more details like logs and/or screenshots  please ?

**Comment by Erhie** [comment] 2016-09-20 15:08
the game runs till Windows VISTA, now in Windows 10 the magnification of 3D graphic is very very too big
after many tried, I began again with a new Win32 prefix for XP using Q4Wine
**the crash report:**
[backtrace_dino_win32qt4_errlog.txt](https://github.com/brezerk/q4wine/files/482902/backtrace_dino_win32qt4_errlog.txt)

the output of
env WINEPREFIX=~/.local/share/wineprefixes/win32qt4 wine Dino.exe &> ~/logs/dino_from_wqt4_log.txt
**is**
[dino_from_qt4_log.txt](https://github.com/brezerk/q4wine/files/482907/dino_from_qt4_log.txt)

Thank you
for thinking about

**Comment by brezerk** [comment] 2016-09-20 19:07
Hi @Erhie 

ic. Unfortunately, q4wine is only front end to the wine project. I'd propose you flowing steps:

1) Retry with clean prefix via q4wine (Create new prefix, do not install anything via winetrinks plugin, e.t.c. just install the app and run). If problem still exists continue with next step.

2) Ensure that q4wine itself does not cause this issue:

- create new wine prefix manually;
- install and run app manually;

Here you are example of terminal commands to use:

```
export WINEPREFIX=$HOME/test_wine
wineboot
wine <path_to_install_file>
cd "$HOME/test_wine/drive_c/Program Files/BBC Science/Dinosaur World" # <-- check the path
wine ./Dino.exe
unset WINEPREFIX
```
If problem still exists continue with next step.
If program runs fine, let me know, we will try to debug to find out the root cause.

3) If problem still exists: check https://appdb.winehq.org/ if there are any known workarounds available for your app. If there are no known bugs or they are not working for you, submit a bug report at http://bugs.winehq.org/ Attach all files and describe all steps needed to reproduce the issue. To reduce number of debug efforts, try to use debug info obtained from the step 2 (i.e. without any third-party apps like q4wine).

I hope it helps.

**Comment by Erhie** [comment] 2016-09-20 22:32
Thank you brezerk,
same crash
I reported
https://bugs.winehq.org/show_bug.cgi?id=41374

Have a good time
Erhy

**Comment by brezerk** [comment] 2016-09-21 16:44
Thanks for reporting. I am going to close this issue. Reopen if needed.

**Closed by brezerk** 2016-09-21 16:44 UTC
Labels: Bug, Support, Unconfirmed
