### ISSUE TITLE
Q4Wine file selectors filters files with upper case extension

### ISSUE THREAD

**Issue by knochenhans** [brezerk/q4wine#94] opened 2016-10-28 22:38 UTC
Hi, hope this is the right place for bugs :)

The file selectors in Q4Wine filters away files which extension are in uppercase (e.g. "WINWORD.EXE"), which makes it cumbersome or even impossible to select such files, because there's no way to turn of the filter completely in the file selector.

I'm using Q4Wine 1.3.2.0 (git via AUR) on Arch Linux with MATE Desktop 1.16.1.

**Comment by brezerk** [comment] 2016-10-29 10:03
Hi Andre

Thank you for bug report.

Just wonder which one Qt library (4.x or 5.x) you are using with q4wine?

**Comment by knochenhans** [comment] 2016-10-29 11:08
Hi, Q4Wine uses Qt 5.7.0 for me.

**Comment by brezerk** [comment] 2016-10-29 11:19
Hi @knochenhans 

I just tried and I am able to see 'TEST.EXE' file in file selector.
![screenshot_20161029_141343](https://cloud.githubusercontent.com/assets/23820/19829140/f14e0544-9de1-11e6-99ea-ca4889cedc03.png)

Was testing both: File -> Run and Programs -> Run -> Browse...

Are you getting this error in some specific place? 
Apparently it is good idea to have ability to disable the filters through =)

**Comment by knochenhans** [comment] 2016-10-29 16:24
I didn't do anything specific, happens to me with File -> Run and Programs -> Run -> Browse.... Here is a screenshot (with a lot files ending on EXE hidden). Not sure why my file selector looks completely different, seems the standard file selector from GTK3 is used in my case. Could this have something to do with the problem?

![q4wine](https://cloud.githubusercontent.com/assets/5293125/19831203/7aa6bd64-9e04-11e6-8132-7c97bd22af42.png)

**Comment by brezerk** [comment] 2016-10-29 17:14
Yeah. Here can be an issue with this...

By default, the native file dialog is used unless you use a subclass of QFileDialog that contains the Q_OBJECT macro, or the platform does not have a native dialog of the type that you require.

So for KDE you will see File Dialog selector created by KDE team instead of Qt build-in.

Also, by default, Qt/KDE file selectors are case insensitive:  http://doc.qt.io/qt-5/qdir.html#Filter-enum Unless `QDir::CaseSensitive` is set. 

I have added `All files (*)` to all file selectors: https://github.com/brezerk/q4wine/commit/848783a6bfa851d448511b5b680f1e60b18c6320 so at least not, you will be able to workaround this.

Also, there is a possibility to force to use Qt build-in dialog, so if you wish, I can add an option for this.

**Comment by kakurasan** [comment] 2016-10-30 03:02
I have the same problem (MATE 1.16.0, GTK+ filechooser). It seems uppercase extensions are needed in the filters, for example:
```diff
--- a/src/q4wine-gui/run.cpp
+++ b/src/q4wine-gui/run.cpp
@@ -340,7 +340,7 @@ void Run::cmdGetProgram_Click(){
     dialog.setWindowTitle(tr("Open Exe file"));
     dialog.setDirectory(searchPath);
     dialog.setFileMode(QFileDialog::ExistingFile);
-    dialog.setNameFilter(tr("Exe, MSI, BAT files (*.exe *.msi *.bat);;Exe files (*.exe);;MSI files (*.msi);;BAT files (*.bat);;All files (*)"));
+    dialog.setNameFilter(tr("Exe, MSI, BAT files (*.exe *.msi *.bat *.EXE *.MSI *.BAT);;Exe files (*.exe *.EXE);;MSI files (*.msi *.MSI);;BAT files (*.bat *.BAT);;All files (*)"));
     //dialog.setSidebarUrls(prefix_urls);
 
 #if QT_VERSION >= 0x040500
```

**Comment by brezerk** [comment] 2016-10-30 15:37
Hi @kakurasan 

I have examined sources for some other Qt projects and none are defining filters with uppercase separately.

I believe this should be fixed in the MATE's file chooser code instead.

I can add uppercase definitions as a temporary workaround, but I will need you to provide a link to bug report for MATE project :)

**Comment by kakurasan** [comment] 2016-10-31 13:16
This is [a bug *in Qt*](https://bugreports.qt.io/browse/QTBUG-51712), not a DE-related bug.

I can see the files with uppercase extensions only when the filter "All files" is selected. This is not the expected behavior because all other filters don't work as expected (but I think adding "All files" is an enhancement).

> there is a possibility to force to use Qt built-in dialog

This is easy but sounds not user-friendly for GTK+ Desktop Environment users.

**Comment by brezerk** [comment] 2016-11-01 21:30
ic. Anyway thanks for the link. Will add an workaround as requested.

**Comment by brezerk** [comment] 2016-11-01 21:57
workaround for https://bugreports.qt.io/browse/QTBUG-51712 has been added as requested: https://github.com/brezerk/q4wine/commit/b7ae42c1eabc73f8eb0df07fc57f79732cf83f13

Thanks for reporting. Reopen if needed.

**Closed by brezerk** 2016-11-01 21:57 UTC
Labels: Bug
